rule-update ossec backup local rules issue Security-Onion-Solutions/security-onion#1572

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -6,7 +6,6 @@ case "$1" in
     configure)
         
 	chmod +x /usr/sbin/rule-update
-	#chmod +x /usr/bin/so-snorby-fix-sigs
 
 	# Package copied rule-update cron job to /etc/nsm/templates/cron.d/rule-update.
 	# Copy this cron job to /etc/cron.d/ but NOT if this is a
@@ -19,6 +18,15 @@ case "$1" in
 		cp /etc/nsm/templates/cron.d/rule-update /etc/cron.d/rule-update
 	fi
         
+	# older versions of rule-update copied local_rules.xml to local_rules_orig.xml which would cause duplicate rule issues with wazuh
+	# rule-update ossec backup local rules issue #1572
+	# https://github.com/Security-Onion-Solutions/security-onion/issues/1572
+	# if the file exists, move it to the backup directory
+	FILE="/var/ossec/rules/local_rules_orig.xml"
+	if [ -f $FILE ]; then
+		mv $FILE /var/ossec/rules/backup/ || echo "Error moving $FILE to /var/ossec/rules/backup/"
+	fi
+
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/usr/bin/rule-update b/usr/bin/rule-update
--- a/usr/bin/rule-update
+++ b/usr/bin/rule-update
@@ -260,8 +260,13 @@ else
 		#if [ ! -f $HIDS_RULES_ORIG ]; then
 		#	cp $HIDS_RULES $HIDS_RULES_ORIG
 		#fi
-		# that now causes issues with Wazuh, so let's remove it if it exists
-		rm -f $HIDS_RULES_ORIG
+		# older versions of rule-update copied local_rules.xml to local_rules_orig.xml which would cause duplicate rule issues with wazuh
+		# rule-update ossec backup local rules issue #1572
+		# https://github.com/Security-Onion-Solutions/security-onion/issues/1572
+		# if the file exists, move it to the backup directory
+		if [ -f $HIDS_RULES_ORIG ]; then
+			mv $HIDS_RULES_ORIG $HIDS/backup/ || echo "Error moving $HIDS_RULES_ORIG to $HIDS/backup/"
+		fi
 
 		# Copy local.rules.xml from master.
 		scp -i "$KEY" $SSH_USERNAME@$SERVERNAME:/tmp/local_rules.xml $HIDS_RULES
